[package]
name = "server-side-shared-state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.4"
rand = "0.8.5"
tokio = { version = "1.25.0", features = ["full"] }
wasmtime = "5.0.0"
