[package]
name = "greeter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 'z'

[dependencies]
wit-bindgen = {git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "462527127f0d9de935f01e298a7e1c975e124a62"}
